### PR TITLE
Added annotation for ssnLast4Provided

### PR DESCRIPTION
**Pull request by sterfried**
@SerializedName Annotation is required for this field because it contains a number.

### CODE REVIEW

**Comment by brandur** [comment]
Sweet! Thank-you once again for taking care of this. Just for gemeral cleanliness, would you mind squashing the imports down here? (i.e. just `git rebase -i master` and change the `pick` to an `f` next to your second commit; then `git push -f origin master`)

**Comment by sterfried** [comment]
Yes, I can do that in a few hours, don't have git or repo on this computer.

**Comment by brandur** [comment]
> Yes, I can do that in a few hours, don't have git or repo on this computer.

Does that mean you were writing these from the web interface?? Wow.

Okay, cool though! Let me know if it's too inconvenient and I can do the rebase over here too.

**Comment by sterfried** [comment]
lol yep, hence the missing import. I did use github's desktop application for making that larger push the other day. I should be home in an hour or two, could use the practice, but since this is technically a bug now, feel free to take care of it if time is an issue.

**Comment by sterfried** [comment]
Yeesh, I think I did that right. I really gotta read up on how git works. If there's anything wrong with all that I'm fine with you making any changes necessary to make it conform, or you can make the annotation change on your end and I'll close this PR. Thanks for your patience!

**Comment by brandur** [comment]
> Yeesh, I think I did that right. I really gotta read up on how git works. If there's anything wrong with all that I'm fine with you making any changes necessary to make it conform, or you can make the annotation change on your end and I'll close this PR. Thanks for your patience!

And thanks again for taking care of this!

All in all, you ended up accidentally pushing some undesirable merge commits into this pull, but you did get the squashed commit that we wanted in 948b9c4, so nice one! I've cherry picked the commit to master and am closing this out.

**Comment by sterfried** [comment]
@brandur thanks again sir!

**Comment by brandur** [comment]
> @brandur thanks again sir!

Anytime!

Released as 1.41.1.

**Comment by sterfried** [comment]
@brandur Does the jar get compiled automatically after a period of time? I notice the new release doesn't have a compiled jar (but all the rest, even incremental versions, do)

**Comment by brandur** [comment]
@sterfried Oh weird! I noticed my release script crashed the first time around. I re-ran, but it's possible that something didn't quite finish up.

Would you mind checking it again? I just rebuilt the artifact and re-released.

**Comment by sterfried** [comment]
Yeah, according to this page https://github.com/stripe/stripe-java/releases it isn't showing the jar.

**Comment by brandur** [comment]
> Yeah, according to this page https://github.com/stripe/stripe-java/releases it isn't showing the jar.

Ah! I thought you were talking about Nexus. You're right — the JAR was indeed missing. I've just added it now, so 1.41.1 should be officially good to go.

**Pull request closed without merging**
