### PR TITLE
Add support for exchange_rates API requests

### PR DESCRIPTION
**Pull request by ob-stripe**
r? @brandur-stripe
cc @stripe/api-libraries @alixander-stripe

Adds support for the new `/v1/exchange_rates` endpoints.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Same for this one if you wouldn't mind OB. `ExchangeRates` -> `ExchangeRate`

**Comment by ob-stripe** [comment]
Done, ptal

**Comment by brandur-stripe** [comment]
@ob-stripe Ah man, sorry one more small thing: both the new files you added are using four-space indents instead of the tabs, which are the standard project convention. Mind doing a quick find and replace?

And man, I really need to add a Travis script that will check for this kind of thing and fail the build :/

**Comment by ob-stripe** [comment]
Oops! Fixed.

**Comment by brandur-stripe** [comment]
Thanks!

**Comment by brandur-stripe** [comment]
Released as 5.23.0.

**Pull request merged**
