### PR TITLE
Added additional personal information fields

### PR DESCRIPTION
**Pull request by sterfried**
Added "personalIdNumberProvided" and "ssnLast4Provided" boolean verification field.

### CODE REVIEW

**Comment by olivierbellone** [comment]
Hi @sterfried, thanks for this PR! However, for boolean fields, we use the `Boolean` class rather than the `boolean` primitive type.

Would you mind refactoring your PR to switch the fields you added to `Boolean`?

**Comment by sterfried** [comment]
Done!

**Comment by olivierbellone** [comment]
Thanks! Looks good to me. cc @brandur

**Comment by brandur** [comment]
Looks good to me! @sterfried Thanks for taking a look at the problem!

One thing: any reason why #252 is in a separate PR? Should we just bring these two patches together into one?

**Comment by sterfried** [comment]
No, no reason besides I'm still new with GitHub (using the web interface) and couldn't seem to find how to combine multiple patches into one PR.

**Comment by brandur** [comment]
> No, no reason besides I'm still new with GitHub (using the web interface) and couldn't seem to find how to combine multiple patches into one PR.

Ah, got it.

If we want to give it a shot, it's pretty simple to get them into one. Just make sure you're in the branch in this patch:

``` sh
git checkout patch-2
```

Then cherry-pick your commit from the other branch:

``` sh
git cherry-pick 5c40379
```

Then push this branch up to GitHub:

``` sh
git push origin master
```

And close #252 because it's no longer needed. Voila!

**Comment by sterfried** [comment]
Sure, give me a few minutes to try to clean that up. Thanks for the insight as I'd like to contribute further.

**Comment by brandur** [comment]
Err, added a small correction to the above: `git push` should be for `patch-2` and not `master`.

> Sure, give me a few minutes to try to clean that up. Thanks for the insight as I'd like to contribute further.

NP! Thanks again.

**Comment by sterfried** [comment]
Okay, I *think* I got that cleaned up. Cheers!

**Comment by brandur** [comment]
Great! Thanks again.

**Pull request merged**
