### PR TITLE
Provide a type-safe API method interface

### PR DESCRIPTION
**Pull request by kjc-stripe**
The current interface for creating and updating records requires manual construction of HashMaps. 

```java
Map<String, Object> planParams = new HashMap<String, Object>();
planParams.put("amount", 5000);
planParams.put("interval", "month");
planParams.put("name", "Gold large");
planParams.put("currency", "usd");
planParams.put("id", "gold-large");
Plan.create(planParams);
```

This pull requests uses Google AutoValue to generate a typed interface for API requests. Creating a plan can now be down in a type-safe manner.

```java
CreatePlan params = CreatePlan.builder()
    .amount(5000)
    .interval("month")
    .name("Gold large")
    .currency("usd")
    .id("gold-large")
    .build()
Plan.create(params);
```

### Breaking changes
If you were calling a method with null before, you'll need to cast or pass an empty value object now.

```diff
-Account account = Account.create(null);
+Account account = Account.create(new HashMap<String, Object>());
```

### TODO
- [x] Support nullable arguments
- [x] Update all methods to include a signature with the correct ValueObject

### Future work
- Support nested input parameters
- Use annotations to instead of `toMap`
- Type safe interface for retrieval methods (`all`, `retrieve`, etc.)

### CODE REVIEW

**Comment by kjc-stripe** [comment]
So I'm not super happy that I needed to pull in a jsr jar to get the `@Nullable` annotation.

**Comment by kjc-stripe** [comment]
Alright, now that this is passing, I'd be interested in hearing feedback. cc @evan-stripe @olivier-stripe @mrmcduff-stripe

**Comment by mrmcduff-stripe** [comment]
I've never seen Google's AutoValue package before -- is there a reason it makes all the fields package-private instead of private? I also really wish that the `toMap` function it (very helpfully) creates was an `@Override` of some interface so that you could know it was there in a group of superclass types.

Otherwise, seems like a good thing. Is this lib particularly large in build size?

**Comment by kjc-stripe** [comment]
@mrmcduff-stripe the `toMap` method is actually my doing. I'm using a script to generate all the files in the `params` package. I can add a `Mappable` interface for all of our auto values, though I'm not sure how useful that would be.

**Comment by mrmcduff-stripe** [comment]
It looks like the only thing in the diff is the conversion to using this new style of model -- just wanted to confirm that before I lgtm-stamp a 3000+ line diff :) @kjc-stripe

**Comment by kjc-stripe** [comment]
Sorry, I should have included a note to all the reviewers. I'm looking for feedback on the proposed interface changes, especially the backwards incompatible change. Basically, a go/no-go decision for this interface. If you vote no-go, I'd love to hear your concerns.

**Comment by kjc-stripe** [comment]
Also, here's the code I used to generate this PR https://gist.github.com/kjc-stripe/6824d1081808906f82f4a0c366bf45b1

**Comment by mrmcduff-stripe** [comment]
I'm all for it. Will wait for others to have a chance to look it over

**Comment by evan-stripe** [comment]
No objections from me

**Comment by remi-stripe** [comment]
I think we need to find a viable solution to the API version pinning only when using the Builder pattern before we can merge. Some of those named parameters only work with the latest API version but the map solution works with all.

**Comment by kjc-stripe** [comment]
So, I sadly don't have to the time right now to get this to completion. I'm going to close this until that happens, or someone else wants to take. 

@remi-stripe If you have time, I'd love to hear your thoughts on how we should do API pinning

**Comment by remi-stripe** [comment]
@kjc-stripe As long as it's behind the builder pattern I think it should be doable to pin to a specific API version. Part of the issue is that if we update it often (and we should) we end up with major versions constantly similarly to the Go library which is not the best solution if we want people to upgrade often.

I'd say that the first step would be to discuss what we want out of this new behavior and make some decisions. This should help unblock shipping this afterwards. cc @brandur-stripe

**Comment by brandur-stripe** [comment]
> So, I sadly don't have to the time right now to get this to completion. I'm going to close this until that happens, or someone else wants to take.

Nooooooo.

Alright, I'm going to try and solicit some interest internally. We have one person coming on who might be in need of a project, so there's hope.

> I'd say that the first step would be to discuss what we want out of this new behavior and make some decisions. This should help unblock shipping this afterwards. cc @brandur-stripe

Yeah. Those ideas have been getting bounced around for a while, but I guess we've never decided on anything. I personally suspect that the major version bumps aren't the end of the world. People don't tend to upgrade their dependencies that often anyway, and when they do, (1) we do a pretty job of documenting the changes, and (2) often changes will be in parts of the library they're not using directly anyway. Deprecating fields also has some nice properties around user friendliness as well; on an API version upgrade instead of fields just silently becoming `null` because they've been removed, at least users will get a compiler error instead.

Remi, what do you think is the best way forward here? Do you want me to write an internal RFC? I have a feeling that this is the type of change that might be relatively uncontentious, but could do well with a rubber stamp if that's the case.

**Comment by remi-stripe** [comment]
> Remi, what do you think is the best way forward here? Do you want me to write an internal RFC? I have a feeling that this is the type of change that might be relatively uncontentious, but could do well with a rubber stamp if that's the case.

I mostly agree. I think we need agreement, likely internally, on the best path forward and how to handle API version changes. We do this in an ad-hoc/random way on stripe-go right now. If two libraries (three if we count stripe-dotnet) end up with enforced API version, we need better documentation to actively upgrade the API version in the bindings whenever a new one is released.

Java is also a bit specific because we will enforce the API version but only for a specific type of integration using the builder. The other solution would be to take this as an opportunity to rework the library completely, only support the builder method moving forward and stop supporting old API versions and custom parameters.

**Comment by brandur-stripe** [comment]
> we need better documentation to actively upgrade the API version in the bindings whenever a new one is released.

Yeah definitely. One thing to maybe note is that this wouldn't too much different than what we're doing right now (or what we should be doing right now) because we're still adding new things to the library, just without the version bump.

> The other solution would be to take this as an opportunity to rework the library completely, only support the builder method moving forward and stop supporting old API versions and custom parameters.

Yeah, this might be a good idea. I suspect that we should wait until we have a much stronger reason for doing it though, because we're going to create some pretty huge legacy if we cut over to something that's totally incompatible.

**Comment by kjc-stripe** [comment]
This pull request is now out-dated and stale. I'm going to close it, but we should open it up in the future when we want to tackle this again.

**Pull request closed without merging**
