### PR TITLE
Autogen params

### LINKED ISSUE #605: Arrays in webhooks previous attributes parsed as Object[]
Hi,

I am using stripe-java version 7.1.0 and I am currently experiencing something weird with Webhooks.
When getting `event.getData().getPreviousAttributes()`, I obtain a `Map<String, Object>` which is fine.

Within this map, if I am getting the field `verification`, is it also a `Map<String, Object>`.
But why an array, like `verification -> fields_needed` is an `Object[]` instead of a `List<Object>`.

Actually, I am asking this question to myself, because with my JSON library (Jackson JSON), When I am using this code: 

```java
String jsonStr = "some json";
Map<String, Object> result = mapper.readValue(jsonStr, Map.class);
``` 

When I am recovering  `verification -> fields_needed`, I am getting an `ArrayList<Object>`. And I find this more natural.

### PR DESCRIPTION
**Pull request by mickjermsurawong-stripe**
This PR now serves as the base for working with stripe java autogen with params
It contains commit that was removed from the original autogen 8.0. The most important being the base work from #679
cc @stripe/api-libraries 
r? @ob-stripe  This is the non-autogen component we discussed yesterday. 
The second commit is already reviewed (containing changes in event data deserializer to use List instead of Array). Actually with this, it should be java 9.0?

Fixes #605.

### CODE REVIEW

**Comment by mickjermsurawong-stripe** [comment]
ack ob! will do. 
thank you!

**Comment by mickjermsurawong-stripe** [comment]
ptal @ob-stripe 
It's ready to merge to integration branch.
- It now has same snapshot as `sdk-autogen-java/pull/58`.
- It contains the renamed class `RunErrorr` so ErrorProne should be good

**Comment by mickjermsurawong-stripe** [comment]
I tried to rebase this on `ErrorPrune` https://github.com/stripe/stripe-java/pull/713 on a separate branch, and built passes fine!

**Comment by ob-stripe** [comment]
itshappening

**Comment by mickjermsurawong-stripe** [comment]
yay! thanks @ob!

**Pull request merged**
