### PR TITLE
Fix link(s) for GSON download since it moved

### PR DESCRIPTION
**Pull request by jlomas-stripe**
¯\\\_(ツ)_/¯

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Good on Google. More GitHub! :)

LGTM.

**Comment by jlomas-stripe** [comment]
...This is not right.  Wait one.

**Comment by jlomas-stripe** [comment]
The only place I can actually find the jar is here:

https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar

**Comment by jlomas-stripe** [comment]
@brandur I was wrong the first time.  It is ... approximately right now. :)

**Comment by brandur-stripe** [comment]
Thanks! Yep, looks fine to my eye.

**Pull request merged**
