### PR TITLE
Enforce no checkstyle issues during build

### PR DESCRIPTION
**Pull request by ob-stripe**
r? @brandur-stripe 
cc @stripe/api-libraries 

Enforce no checkstyle issues during builds.

### CODE REVIEW

**Comment by brandur-stripe** [comment]
The day of reckoning!

LGTM, but it looks like the build failed under OpenJDK 7:

```
* What went wrong:
Execution failed for task ':checkstyleMain'.
> com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask : Unsupported major.minor version 52.0
```

Maybe it's too old a version to support this task?

ptal @ob-stripe

**Comment by ob-stripe** [comment]
Sigh. Of course the most recent version of Checkstyle requires Java 8. I'll look for a workaround.

**Comment by ob-stripe** [comment]
Okay, it's not the most elegant solution, but I modified `.travis.yml` to only run the `check` task with Java 9.

**Comment by brandur-stripe** [comment]
> Okay, it's not the most elegant solution, but I modified .travis.yml to only run the check task with Java 9.

Yeah, it's not perfect, but that seems like the right move.

**Pull request merged**
