### PR TITLE
Dependency inject network requests in APIResource

### PR DESCRIPTION
**Pull request by danwang**
r? @bkrausz 

This isn't really dependency injection, but it's close enough to fix testing so they become useful again.

This is a huge diff, so summary:
- Added a `StripeResponseGetter` interface that has a single `request` method.
- Moved `private static` functions dealing with network requests from `APIResource` to `LiveStripeResponseGetter < StripeResponseGetter`. This is mostly copy and paste, with a few exceptions where shared things stay on `APIResponse`.

TODO
- [x] clean up unnecessary imports

### CODE REVIEW

**Comment by bkrausz** [comment]
Defer entirely to @jimdanz on this, as he knows Java patterns better than I do.

**Comment by danwang** [comment]
Not sure why CI is failing, but tests pass locally half the time:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.stripe.DocumentationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.048 sec
Running com.stripe.model.DeserializerTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.119 sec
Running com.stripe.model.StandardizationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.212 sec
Running com.stripe.StripeTest
Tests run: 155, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 132.505 sec

Results :

Tests run: 167, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2015-03-16T17:03:29-07:00
[INFO] Final Memory: 8M/81M
[INFO] ------------------------------------------------------------------------
```

**Comment by shalecraig** [comment]
Only looking at this at a glance: this should work. I'm not sure why the documentation test is failing.

A `StripeSession` with its own `StripeResponseGetter` (and a few other things) would be so much better.

**Comment by bkrausz** [comment]
HOLY SHIT GUYS IT'S @shalecraig!!!!!



Also this is just test structure, if it's blocking other stuff I'd feel free to :shipit: and review post-merge.

**Comment by jimdanz** [comment]
I wouldn't call this "just test structure" since it's touching real code, but I'm bullish on this direction.

That said, if it's going to be static, why not have it be global to the `Stripe` class?  As this stands it feels like it'd be a fair bit of struggle to thread your `StripeResponseGetter` through to all the classes that need it, but maybe that's intentional?

basically: happy to have this be merged to master as-is, but I'm not sure that I "get" it without seeing tests rewritten against it

**Comment by danwang** [comment]
Opened #149, which stubs out the network portion.

`StripeResponseGetter` applies to all of the `APIResource` methods because they all end up using `request` (formerly `_request`) at one point. It could go in the global `Stripe` class, but I think it makes more sense as a dependency of `APIResource`.

**Comment by jimdanz** [comment]
Ah OK my mistake -- I think I was thinking about it wrong!

**Pull request merged**
