### PR TITLE
Add invoice's url and pdf properties

### PR DESCRIPTION
**Pull request by remi-stripe**
Fixes https://github.com/stripe/stripe-java/issues/514

r? @brandur-stripe 
cc @stripe/api-libraries

### CODE REVIEW

**Comment by brandur-stripe** [comment]
Haha, beat me to it Remi!

This looks good to me. @ob-stripe would you mind taking a quick look at this as well? Looking around the code, I couldn't figure out whether we're trying to move towards `hostedInvoicePDF` or `hostedInvoicePdf`. It looks to me like what Remi's put here is right (based on lots of `Id` properties elsewhere), but we've got a pretty crazy mix throughout.

**Comment by ob-stripe** [comment]
In [version 2.0.0](https://github.com/stripe/stripe-java/blob/master/CHANGELOG.md#200---2016-04-08) we changed a bunch of accessors from `Url` to `URL`, so I think we should stick to all uppercase for acronyms, at least for accessors.

It looks like we're not handling this very consistently through the library though:
- either the attribute itself uses all uppercase, in which case we need a `@SerializedName` annotation, e.g.: https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/ThreeDSecure.java#L33
- or the attribute only capitalizes the first letter of the acronym, in which case we need to manually create the accessors (otherwise Lombok would use the same capitalization as the attribute), e.g.: https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/model/SourceRedirectFlow.java#L13

I have a slight preference for the first, as it's less verbose and more consistent.

**Comment by remi-stripe** [comment]
yeah I looked at a random one and likely chose the wrong thing. I will fix.

**Comment by remi-stripe** [comment]
fixed, PTAL

**Comment by remi-stripe** [comment]
Okay so I pushed the change to keep the capitalized version. But I think that if we have to add custom logic to serialize those, we likely should default to the other approach and keep `Url` and `Pdf` instead.

**Comment by ob-stripe** [comment]
> But I think that if we have to add custom logic to serialize those, we likely should default to the other approach and keep `Url` and `Pdf` instead.

Switching to capitalizing only the first letter would also make us 100% compliant with Google's Java style rules[0], so I'd be in favor of that in the next major release.

For now, pulling this in.

[0] https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

**Pull request merged**
