### PR TITLE
Add expanded charge field to Invoice

### PR DESCRIPTION
**Pull request by jboolean**
Similar to #328, which overlooked the expandable `charge` field on Invoice. Works toward #268.

### CODE REVIEW

**Comment by dpetrovics-stripe** [comment]
Thanks @jboolean for adding this functionality, and the fix to use the current context for deserialization.

LGTM

**Comment by jboolean** [comment]
No problem! We have a pretty nasty workaround to retrieve all charges and match them to a set of invoices that I'd love to kill off.

**Comment by dpetrovics-stripe** [comment]
Released as 3.5.0

**Comment by jboolean** [comment]
Future feature: supporting expanding changes on requests without parameters, like retrieve invoice by id.

**Pull request merged**
