### PR TITLE
Add unit_label to the Product class

### PR DESCRIPTION
**Pull request by remi-stripe**
Similar to what was done in https://github.com/stripe/stripe-dotnet/pull/1250

r? @brandur-stripe

### CODE REVIEW

**Comment by brandur-stripe** [comment]
LGTM.

**Comment by brandur-stripe** [comment]
Released as 6.5.0.

**Comment by karlr-stripe** [comment]
It looks like this release(6.5.0) didn't get pushed to Maven either, like in https://github.com/stripe/stripe-java/pull/572#issuecomment-413378584 : https://mvnrepository.com/artifact/com.stripe/stripe-java 

Is there anything we can do?

**Comment by ob-stripe** [comment]
I've just released the repository on Sonatype. The release should appear on Maven within a few hours.

**Pull request merged**
