### PR TITLE
stripe-java 6.0.0

### LINKED ISSUE #409: Deserializing resources should work even if the resource is deleted
When you delete a resource in Stripe, it is returned as a limited object with just an `id` and `deleted: true`. In Java, those resources are custom classes called `DeletedAccount` for example.

When you retrieve a resource and expand specific fields, some of those fields might represent a deleted resource. If you use a custom deserializer though you can end up with a crash because the deserializer did not account for deleted resource.

An example is trying to retrieve a `Payout` that has been sent to a bank account (external account) deleted since then. The resource returned is not deserialized properly.

The callstack is
```
Exception in thread "main" java.lang.NullPointerException
	at com.stripe.model.ExternalAccountTypeAdapterFactory$1.read(ExternalAccountTypeAdapterFactory.java:41)
	at com.stripe.model.ExternalAccountTypeAdapterFactory$1.read(ExternalAccountTypeAdapterFactory.java:33)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:859)
	at com.google.gson.Gson$2.deserialize(Gson.java:131)
	at com.stripe.model.ExpandableFieldDeserializer.deserialize(ExpandableFieldDeserializer.java:36)
	at com.stripe.model.ExpandableFieldDeserializer.deserialize(ExpandableFieldDeserializer.java:8)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:93)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:172)
	at com.google.gson.Gson.fromJson(Gson.java:795)
	at com.google.gson.Gson.fromJson(Gson.java:761)
	at com.google.gson.Gson.fromJson(Gson.java:710)
	at com.google.gson.Gson.fromJson(Gson.java:682)
	at com.stripe.net.LiveStripeResponseGetter._request(LiveStripeResponseGetter.java:447)
	at com.stripe.net.LiveStripeResponseGetter.request(LiveStripeResponseGetter.java:66)
	at com.stripe.net.APIResource.request(APIResource.java:161)
	at com.stripe.model.Payout.retrieve(Payout.java:271)
```

The code causing the issue lives [here](https://github.com/stripe/stripe-java/blob/da0f8208e7505b635508d09e7bd38686ed9f9790/src/main/java/com/stripe/model/ExternalAccountTypeAdapterFactory.java#L41) though there might be other custom deserializers impacted.

### PR DESCRIPTION
**Pull request by ob-stripe**
- [x] Remove deprecated methods flagged for removal (#532)
- [x] Only capitalize the first letter of acronyms per Google's style rules (#534)
- [x] Change signatures to throw `StripeException` (#535)
- [x] Use `isX()` instead of `getX()` for Boolean accessors (#536)
- [x] Change all integer types to `Long` and all floating point types to `Double` (#538)
- [x] Add support for idempotency errors (#540)
- [x] Minor fixes (#541)
- [x] Move nested objects into inner static classes (#547)
- [x] Remove `Deleted` models and add `deleted` attribute instead (#553)
- [x] Use `BigDecimal` for floating point values (#558)

Fixes #409 (via #553).

### CODE REVIEW

**Comment by codylerum** [comment]
@ob-stripe RE: https://github.com/stripe/stripe-java/pull/536#issuecomment-399557031 

If that effects the `Boolean` object as well you may want to change those to `boolean` to conform with the Java Beans spec 8.3.2 (http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/) 

`is` is allowed for `boolean` but not `Boolean`

**Comment by codylerum** [comment]
Any chance of using BigDecimal instead of doubles?

**Comment by ob-stripe** [comment]
> Any chance of using BigDecimal instead of doubles?

Hey @codylerum, sorry, I'm only seeing your comment now! Using `BigDecimal` is less convenient than `Double` due to arithmetic operators not being overloaded. That said, when dealing with money, it's definitely preferable to use `BigDecimal` to avoid rounding errors.

@brandur-stripe @remi-stripe wdyt? I'm personally in favor of it. It will make the library less convenient to use where floating-point values are concerned (e.g. exchange rates), but the added precision is worth it IMO.

**Comment by remi-stripe** [comment]
@ob-stripe Would you be able to give some examples of code that would be different if we moved to it? Like what would be less convenient and what can't you do as easily?

**Comment by ob-stripe** [comment]
Here's an example:

```java
Long amountInEur = 499; // 4.99 EUR
Double exchangeRate = ExchangeRate.retrieve("eur").getRates().get("usd");
Long amountInUsd = Long.valueOf(Math.round(amountInEur * exchangeRate));
```

vs.

```java
Long amountInEur = 499; // 4.99 EUR
BigDecimal exchangeRate = ExchangeRate.retrieve("eur").getRates().get("usd");
Long amountInUsd = Long.valueOf(exchangeRate.multiply(new BigDecimal(amountInEur)).setScale(0, BigDecimal.ROUND_HALF_UP).intValue());
```

Basically, you have to use `BigDecimal`'s methods like `multiply()` to perform arithmetics, which means that all other factors involved must also be converted to `BigDecimal`s.

**Comment by remi-stripe** [comment]
Oh wow, that is quite wordy and painful. I would hate to have to do that if I was using the library though I am not a Java developer so I don't know how common this library is in the wild. Do you know of other SDKs like ours that would be using BigDecimal?
Also is there a way to improve this by overloading arithmetic operators ourselves?

**Comment by ob-stripe** [comment]
> Also is there a way to improve this by overloading arithmetic operators ourselves?

No, Java doesn't support operator overloading at all.

One thing I didn't mention is that for users who don't really care for the added precision, they can simply convert the value to a regular floating-point by calling `.doubleValue()` on the `BigDecimal` instance provided by the library.

**Comment by codylerum** [comment]
@remi-stripe @ob-stripe Yes it is wordy (slightly simpler than @ob-stripe example) as BigDecimal can go direct to long.

`Long amountInUsd = exchangeRate.multiply(new BigDecimal(amountInEur)).setScale(0, BigDecimal.ROUND_HALF_UP).longValue();`

But anyone working with floating point in Java with money is/should be using BigDecimal

https://blogs.oracle.com/corejavatechtips/the-need-for-bigdecimal

**Comment by codylerum** [comment]
There is definitely an argument for leaving it as the primitive Double and letting the user convert to BigDecimal on their own.

Any Java developer should definitely be converting it to a BigDecimal doing their math with BigDecimal though if it involves math involves money.

**Comment by ob-stripe** [comment]
r? @brandur-stripe @remi-stripe 
cc @stripe/api-libraries 

I think this is ready for release. Each of the individual PRs has already been reviewed, so don't feel like you have to review each of the 253 modified files :)

**Pull request merged**
