### PR TITLE
Move from Maven to Gradle

### PR DESCRIPTION
**Pull request by brandur**
This is a minimized patch based on the work by @mrmcduff-stripe here: https://github.com/stripe/stripe-java/pull/416

### CODE REVIEW

**Comment by mrmcduff-stripe** [comment]
Should I claim the diff and have you approve it for landing?

**Comment by brandur-stripe** [comment]
> Should I claim the diff and have you approve it for landing?

@mrmcduff-stripe Yeah, that'd be fine. If you want to open a new PR, we can close this one.

**Comment by brandur-stripe** [comment]
@mrmcduff-stripe And actually, I just amended my commit to include a fix for a failing test, so make sure that you get the right patch.

**Comment by brandur-stripe** [comment]
And did one last amendment to fix the instructions for running a single test with Gradle in the `README.md`. Hopefully that's the last one.

**Comment by brandur-stripe** [comment]
@mrmcduff-stripe Good news! I think that the update on the Central Repo's HTML site might just take a really _really_ long time (as in it might only refresh every 24 hours or maybe even less frequently). I now see both versions that I pushed last week on here even though I was still seeing nothing on Friday night:

https://mvnrepository.com/artifact/com.stripe/stripe-java

Thanks again for all the help here. I think we've now tied up every loose end and it's safe to call this "done done".

**Pull request merged**
