### PR TITLE
Add HTTP status code to all exceptions.

### LINKED ISSUE #222: Adds http status code to InvalidRequestException
There is currently no way in the Java api bindings to tell the difference between a 404 and a 400 response. These are both identically mapped to InvalidRequestException.

Example use case:
Getting the upcoming invoice for a customer. There is a meaningful difference between a 'not found' vs a 'bad request' response.

### PR DESCRIPTION
**Pull request by kyleconroy**
If there wasn't an HTTP request, the status code will be 0.

Fix #222

### CODE REVIEW

**Comment by cupcait** [comment]
:+1:

**Comment by jimdanz** [comment]
Can I register my vote for fixing the 404 vs 400 issue explicitly (ie, adding a `NotFoundException`) instead of this?  I'm a fan of mapping HTTP status codes to specific exception classes (but admittedly I'd missed the 404 vs 400 issue).

**Comment by kyleconroy** [comment]
@jimdanz I'm fine with that solution, but I don't think there is a good reason to hide the HTTP status code from end users.

**Comment by jimdanz** [comment]
I guess the only reason is potentially confusion.  "APIException is always a 500, so what's getStatusCode()?" but fine with it if you think peaceful.

**Comment by kyleconroy** [comment]
It wouldn't always be a `500`. It's possible that they ran into an upstream gateway timeout and got back a 504. I do think it would be helpful to have a `NotFoundException`, but that would be a breaking change so we'd have to bump to 2.0.

**Pull request merged**
