### PR TITLE
Replace code.stripe.com with Github Releases

### PR DESCRIPTION
**Pull request by nelhage**
r? @jimdanz

### CODE REVIEW

**Comment by jimdanz** [comment]
lg

**Comment by nelhage** [comment]
@jimdanz are those test failures expected?

**Comment by jimdanz** [comment]
@nelhage looks like that's do to the card/source rename.  /cc @maxwells , do we need to get some code merged into stripe-java to unbreak the build?

**Comment by maxwells** [comment]
yes - the binding test keys are on the newest API version. I'm rolling bindings now -- waiting for java tests to pass before merging

**Comment by maxwells** [comment]
blocking on a small API bug -- gonna roll a fix shortly.

**Comment by nelhage** [comment]
Ok. Can I merge this anyways since it's unrelated, or should I wait and rebase?

**Comment by maxwells** [comment]
feel free to merge -- I'll rebase

**Pull request merged**
