### PR TITLE
Remove subscriptions from customer

### PR DESCRIPTION
**Pull request by jack-stripe**
I also made sure that Customer is expandable on Subscription.

### CODE REVIEW

**Comment by brandur** [comment]
Hey Jack, thanks a lot for the initiative in putting these together!

Just a couple quick notes/questions:

1. Can you make sure that your whitespace is matching what's in the project already (I think it uses tab characters largely).
2. API version `2017-01-18` isn't actually a real thing is it? https://stripe.com/docs/upgrades
3. I'm not sure that we can change the type of the customer field on subscription without a breaking change :/ That's not the end of the world, but we might want to instead just pool some of these up and release them all in one go.

**Comment by jack-stripe** [comment]
@brandur-stripe - similarly to the equivalent golang PR, I'll hold off on doing anything here until the API change is out.

**Comment by brandur** [comment]
Cool! As with https://github.com/stripe/stripe-go/pull/360, I'm going to close this for now, but feel free to reopen whenever.

**Pull request closed without merging**
