### PR TITLE
added structure to support unified customer sources api

### PR DESCRIPTION
**Pull request by maxwells**
cc @canderson, @raycmorgan

### CODE REVIEW

**Comment by jimdanz** [comment]
lg. Is there a reason that PaymentSource and DeletedStripeObject need to be interfaces, instead of classes that extend, respectively APIResource and StripeObject?

**Comment by jimdanz** [comment]
Oh, just reread and apparently PaymentSource used to be a class, so I'm assuming there's a reason :)

**Comment by maxwells** [comment]
there's no requirement -- I just preferred it for PaymentSource (having all the prop getters/setters and public interface for a class within its own file). I have no feelings one way or the other about DeletedStripeObject

**Comment by jimdanz** [comment]
kk, sg.  :ship:

**Pull request closed without merging**
