### PR TITLE
stripe-java v17

### PR DESCRIPTION
**Pull request by ob-stripe**
Integration branch for the HTTP client refactoring work.

(⚠️ = breaking changes)

- [x] Refactor form encoding (#857)
- [x] ⚠️ Refactor request telemetry (#870)
- [x] Move HTTP request methods into new `HttpClient` class (#872)
- [x] Add `StripeRequest` object (#878)
- [x] Add `HttpClient` abstract class (#879)
- [x] ⚠️ Stop disabling the DNS cache (#880)
- [x] Fix deprecation warnings (#895)
- [x] Add `HttpContent` class (#896)
- [x] Add `Stopwatch` class (#897)
- [x] Move all request properties in `StripeRequest` (#898)
- [x] ⚠️ Remove `ApiResource.RequestType` (#899)
- [x] Add support for automatic request retries (#900)
- [x] Minor fixes (#902)
- [x] `StringUtils` class & better API key validation (#928)
- [x] ⚠️ Remove support for custom `URLStreamHandler` (#927)
- [x] ⚠️ Refactor HTTP headers handling (#931)
- [x] ⚠️ Modernize `StripeResponse` (#932)
- [x] Add `maxNetworkRetries` as a global and per-request setting (#934)
- [x] ⚠️ Add `StreamUtils` class (#935)
- [x] ⚠️ Remove support for `count` and `total_count` in list objects (#936)
- [x] ⚠️ Remove deprecated properties and parameters (#938)
- [x] Update README (#939)

### CODE REVIEW

**Comment by rattrayalex-stripe** [comment]
Can we be sure to include docs on using the retry feature?

**Comment by ob-stripe** [comment]
Okay, I think is ~ready.

I would also like to refactor `StripeResponseGetter` at some point to turn it into a proper `StripeClient` that holds configuration values, but that's a bit of a larger refactor that will also require changes to codegen (since right now every resource class creates full URLs by directly relying on the global configuration, e.g. `Stripe.getApiBase() + "/v1/customers"`).

There's no immediate benefit to doing that though, so I'll probably do that in the future when we introduce service classes. For now we can release this which gives us a cleaner/better foundation as well as support for automatic request retries.

**Comment by ob-stripe** [comment]
r? @brandur-stripe @richardm-stripe @remi-stripe 
cc @stripe/api-libraries 

All PRs have been individually reviewed, so this is really more of a last sweep to see if anything's amiss.

I've also drafted a migration guide to describe the new features and breaking changes: https://github.com/stripe/stripe-java/wiki/%5Bwip%5D-Migration-guide-for-v17.

If there are no objections, I will merge and release this later this week.

**Comment by ob-stripe** [comment]
> you meant the very last header ("Custom URLStreamHandler") to be an h4 instead of an h3

Good eye! Fixed, thanks :)

**Comment by ob-stripe** [comment]
Released as 17.0.0.

**Pull request merged**
