### PR TITLE
Bump version to 1.24.1

### PR DESCRIPTION
**Pull request by mlmanapat**
r? @berg

### CODE REVIEW

**Comment by berg** [comment]
I think you'll need to update the version constant in `src/main/java/com/stripe/Stripe.java` as well.

**Comment by mlmanapat** [comment]
Thanks, done

**Comment by shalecraig** [comment]
Can you release a new version of stripe-java after releasing? (to maven central/etc)

cc @jimdanz

**Comment by mlmanapat** [comment]
Yep that was the motivation for this

**Comment by mlmanapat** [comment]
(Tried to release 1.24.0 but there was some divergence)

**Pull request merged**
